### PR TITLE
update about page text: add instructions for using the CKAN API

### PR DESCRIPTION
**Pull request by OriHoch**
Add instructions for using the CKAN API to the about page

This is following discussions on Twitter which started here: https://twitter.com/idoklein1/status/1320648314224844801

### CODE REVIEW

**Comment by datagov18** [comment]
fixed.

**Comment by OriHoch** [comment]
could you please elaborate - how was it fixed? the PR is not merged, and there is no instructions for using the CKAN API on the site..

**Comment by datagov18** [comment]
Hello,
following your initial enquiry about the version number update, we uploaded the correction of the version number text.
For administrative reasons, we then decided to separate the data from the content management and transfer the site’s content management to another platform, and not manage it in Ckan.
As a result, we cannot accept your contribution as we no longer manage the about page on our site.
Additionally, you can find examples of API usage on the new platform.

**Comment by OriHoch** [comment]
did you read the changes I suggested in this PR?

your site only shows examples for 1 API method, it does not mention that users can use the full CKAN API and how they can do that, which is what this PR adds

regarding your diversion from open soucre, this is shameful and totally inconsistent with the AGPL license requirements, but that's another matter..

**Pull request closed without merging**
